name: rucja
description: "connect_patient_to_doctor"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  flutter_mobx: ^2.2.1+1
  awesome_notifications: ^0.9.3+1
  flutter_localization: ^0.2.1

  fluttertoast: ^8.2.8
  intl: ^0.19.0
  logger: ^2.4.0


  #Notification
#  onesignal_flutter: ^5.2.3

  #Image
  cached_network_image: ^3.4.0
  url_launcher: ^6.3.0
  photo_view: ^0.15.0
  flutter_vector_icons: ^2.0.0

  #Firebase
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.4
  firebase_auth: ^5.1.4

  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1
  country_code_picker: ^3.0.0
  lottie: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


dependencies_overrides:

flutter:
  uses-material-design: true

  assets:
     - assets/
